---
- name: Run mac-pools sub-role
  import_role:
    name: "oVirt.infra/roles/oVirt.mac-pools"

- name: Run datacenters sub-role
  import_role:
    name: "oVirt.infra/roles/oVirt.datacenters"

- name: Run clusters sub-role
  import_role:
    name: "oVirt.infra/roles/oVirt.clusters"

- name: Run hosts sub-role
  import_role:
    name: "oVirt.infra/roles/oVirt.hosts"

- name: Run networks sub-role
  import_role:
    name: "oVirt.infra/roles/oVirt.networks"

- name: Run storages sub-role
  import_role:
    name: "oVirt.infra/roles/oVirt.storages"

- name: Run aaa-jdbc sub-role
  import_role:
    name: "oVirt.infra/roles/oVirt.aaa-jdbc"

- name: Run external-providers sub-role
  import_role:
    name: "oVirt.infra/roles/oVirt.external-providers"

- name: Run permissions sub-role
  import_role:
    name: "oVirt.infra/roles/oVirt.permissions"
